-- Put your schema here. This is the exact schema that will be created
-- when you run `sqlsimple init-db`. 
--
-- When making changes to this schema, it is up to you to create a
-- corresponding migration. The reverse is also true.
--
-- It is also your job to keep any fixtures up to date with this
-- schema.
